 # Column configuration
0: 
  name: mp_number
  non_zero:
  list_items: [MP406, MP409, MP418, MP420, MP424, MP430, MP433, MP479, MP514, MP516, MP639, MP676, MP699, MP709, MP720, MP721]
1:
  name: station_number
  non_zero:
2:
  name: date
  non_zero:
3:
  name: sample_time
  non_zero:
4:
  name: sampling_number
  non_zero:
5:
  name: location_id
  non_zero:
6:
  name: sample_cid
  non_zero:
7:
  name: sample_matrix
  non_zero:
  list_items: [ST, SG, GB, GP, PR]
8:
  name: sample_type
  non_zero:
  list_items: [P, R, D, T, QR, QB, QT]
9:
  name: calibration_record
  non_zero:
10:
  name: sampling_instrument
  non_zero:
  list_items: [Hydrolab DS5, Hydrolab MS4, Hydrolab MS5]
11:
  name: sampling_officer
  non_zero:
  list_items:
    - Alison Lewis
    - Andy Wise
    - Brad Mouat
    - Claire Evans
    - Dan Poflotski
    - Dane Clarke
    - Daniel Irving
    - Darice Pepper
    - David Donnelly
    - Dean Jukes
    - Gerhard Schulz
    - Gordon Honeyman
    - James Hitchcock
    - Jane Rowlands
    - Luke Cruikshank
    - Maxine Rowley
    - Michael Rowe
    - Monika Muschal
    - Peter Klowss
    - Phillip Cocks
    - Sarah McGeoch
    - Skye Taylor
    - Sue Botting
    - Tracy Fulford
    - Warwick Mawhinney
12:
  name: sample_collected
  non_zero:
  list_items:
    - 'Yes'
    - 'No'
13:
  name: depth_upper
  non_zero:
  lower_limit: 0
  upper_limit: 50
  precision: 2
14:
  name: depth_lower
  non_zero:
  lower_limit: 0
  upper_limit: 50
  precision: 2
15:
  name: do
  non_zero: y
  lower_limit: 0
  upper_limit: 50
  precision: 2
16:
  name: do_sat
  non_zero: y
  lower_limit: 0
  upper_limit: 200
  precision: 2
17:
  name: ph
  non_zero: y
  lower_limit: 0
  upper_limit: 14
  precision: 2
18:
  name: temp_c
  non_zero: y
  lower_limit: 0
  upper_limit: 50
  precision: 2
19:
  name: conductivity_uncomp
  non_zero: y
  lower_limit: 0
  upper_limit: 5000000
  precision: 1
20:
  name: conductivity_comp
  non_zero: y
  lower_limit: 0
  upper_limit: 5000000
  precision: 1
21:
  name: turbidity
  non_zero: y
  lower_limit: 0
  upper_limit: 5000
  precision: 2
22:
  name: water_depth
  non_zero:
  lower_limit: 0
  upper_limit: 200
  precision: 2
23:
  name: gauge_height
  non_zero:
  lower_limit: -300
  upper_limit: 1000
  precision: 2
24:
  name: sampling_comment
  non_zero:
