 # Column configuration
0: 
  name: mp_number
  allow_zero:
  required: yes
  list_items: [MP406, MP409, MP418, MP420, MP424, MP430, MP433, MP479, MP514, MP516, MP639, MP676, MP699, MP709, MP720, MP721]
1:
  name: station_number
  allow_zero:
  required: yes
2:
  name: date
  allow_zero:
  required: yes
3:
  name: sample_time
  allow_zero:
  required: yes
4:
  name: sampling_number
  allow_zero:
  required: no
5:
  name: location_id
  allow_zero:
  required: yes
6:
  name: sample_cid
  allow_zero:
  required: yes
7:
  name: sample_matrix
  allow_zero:
  required: yes
  list_items: [ST, SG, GB, GP, PR]
8:
  name: sample_type
  allow_zero:
  required: yes
  list_items: [P, R, D, T, QR, QB, QT]
9:
  name: calibration_record
  allow_zero:
  required: no
10:
  name: sampling_instrument
  allow_zero:
  required: yes
  list_items: [Hydrolab DS5, Hydrolab MS4, Hydrolab MS5]
11:
  name: sampling_officer
  allow_zero:
  required: yes
  list_items:
    - Alison Lewis
    - Andy Wise
    - Brad Mouat
    - Claire Evans
    - Dan Poflotski
    - Dane Clarke
    - Daniel Irving
    - Darice Pepper
    - David Donnelly
    - Dean Jukes
    - Gerhard Schulz
    - Gordon Honeyman
    - James Hitchcock
    - Jane Rowlands
    - Luke Cruikshank
    - Maxine Rowley
    - Michael Rowe
    - Monika Muschal
    - Peter Klowss
    - Phillip Cocks
    - Sarah McGeoch
    - Skye Taylor
    - Sue Botting
    - Tracy Fulford
    - Warwick Mawhinney
12:
  name: sample_collected
  allow_zero:
  required: no
  list_items: ['Yes', 'No']
13:
  name: depth_upper
  allow_zero:
  required: yes
  lower_limit: 0
  upper_limit: 50
  precision: 2
14:
  name: depth_lower
  allow_zero:
  required: no
  lower_limit: 0
  upper_limit: 50
  precision: 2
15:
  name: do
  allow_zero: no
  required: no
  lower_limit: 0
  upper_limit: 50
  precision: 2
16:
  name: do_sat
  allow_zero: no
  required: no
  lower_limit: 0
  upper_limit: 200
  precision: 2
17:
  name: ph
  allow_zero: no
  required: no
  lower_limit: 0
  upper_limit: 14
  precision: 2
18:
  name: temp_c
  allow_zero: no
  required: no
  lower_limit: 0
  upper_limit: 50
  precision: 2
19:
  name: conductivity_uncomp
  allow_zero: no
  required: no
  lower_limit: 0
  upper_limit: 5000000
  precision: 1
20:
  name: conductivity_comp
  allow_zero: no
  required: no
  lower_limit: 0
  upper_limit: 5000000
  precision: 1
21:
  name: turbidity
  allow_zero: no
  required: no
  lower_limit: 0
  upper_limit: 5000
  precision: 2
22:
  name: water_depth
  allow_zero:
  required: no
  lower_limit: 0
  upper_limit: 200
  precision: 2
23:
  name: gauge_height
  allow_zero:
  required: no
  lower_limit: -300
  upper_limit: 1000
  precision: 2
24:
  name: sampling_comment
  allow_zero:
  required: no
