# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fdfGui-V01-2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1139, 873)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 9)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.groupBoxFileDetails = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.groupBoxFileDetails.sizePolicy().hasHeightForWidth())
        self.groupBoxFileDetails.setSizePolicy(sizePolicy)
        self.groupBoxFileDetails.setObjectName(_fromUtf8("groupBoxFileDetails"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBoxFileDetails)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelInstrument = QtGui.QLabel(self.groupBoxFileDetails)
        self.labelInstrument.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInstrument.sizePolicy().hasHeightForWidth())
        self.labelInstrument.setSizePolicy(sizePolicy)
        self.labelInstrument.setMinimumSize(QtCore.QSize(100, 0))
        self.labelInstrument.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelInstrument.setObjectName(_fromUtf8("labelInstrument"))
        self.horizontalLayout_5.addWidget(self.labelInstrument)
        self.instrumentComboBox = QtGui.QComboBox(self.groupBoxFileDetails)
        self.instrumentComboBox.setMinimumSize(QtCore.QSize(133, 0))
        self.instrumentComboBox.setObjectName(_fromUtf8("instrumentComboBox"))
        self.horizontalLayout_5.addWidget(self.instrumentComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelFileLocation = QtGui.QLabel(self.groupBoxFileDetails)
        self.labelFileLocation.setObjectName(_fromUtf8("labelFileLocation"))
        self.horizontalLayout_4.addWidget(self.labelFileLocation)
        self.filePickerBtn = QtGui.QToolButton(self.groupBoxFileDetails)
        self.filePickerBtn.setObjectName(_fromUtf8("filePickerBtn"))
        self.horizontalLayout_4.addWidget(self.filePickerBtn)
        self.fileLineEdit = QtGui.QLineEdit(self.groupBoxFileDetails)
        self.fileLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLineEdit.sizePolicy().hasHeightForWidth())
        self.fileLineEdit.setSizePolicy(sizePolicy)
        self.fileLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.fileLineEdit.setObjectName(_fromUtf8("fileLineEdit"))
        self.horizontalLayout_4.addWidget(self.fileLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.addFileBtn = QtGui.QPushButton(self.groupBoxFileDetails)
        self.addFileBtn.setObjectName(_fromUtf8("addFileBtn"))
        self.verticalLayout_3.addWidget(self.addFileBtn)
        self.horizontalLayout.addWidget(self.groupBoxFileDetails)
        self.layoutCurrentFilesVertical = QtGui.QVBoxLayout()
        self.layoutCurrentFilesVertical.setObjectName(_fromUtf8("layoutCurrentFilesVertical"))
        self.labelCurrentFiles = QtGui.QLabel(self.centralwidget)
        self.labelCurrentFiles.setObjectName(_fromUtf8("labelCurrentFiles"))
        self.layoutCurrentFilesVertical.addWidget(self.labelCurrentFiles)
        self.listWidgetCurrentFiles = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetCurrentFiles.sizePolicy().hasHeightForWidth())
        self.listWidgetCurrentFiles.setSizePolicy(sizePolicy)
        self.listWidgetCurrentFiles.setMinimumSize(QtCore.QSize(400, 0))
        self.listWidgetCurrentFiles.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidgetCurrentFiles.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetCurrentFiles.setObjectName(_fromUtf8("listWidgetCurrentFiles"))
        self.layoutCurrentFilesVertical.addWidget(self.listWidgetCurrentFiles)
        self.horizontalLayout.addLayout(self.layoutCurrentFilesVertical)
        self.groupBoxEditTools = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.groupBoxEditTools.sizePolicy().hasHeightForWidth())
        self.groupBoxEditTools.setSizePolicy(sizePolicy)
        self.groupBoxEditTools.setObjectName(_fromUtf8("groupBoxEditTools"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxEditTools)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButtonDeleteLines = QtGui.QPushButton(self.groupBoxEditTools)
        self.pushButtonDeleteLines.setObjectName(_fromUtf8("pushButtonDeleteLines"))
        self.gridLayout_3.addWidget(self.pushButtonDeleteLines, 2, 0, 1, 1)
        self.pushButtonAddLines = QtGui.QPushButton(self.groupBoxEditTools)
        self.pushButtonAddLines.setObjectName(_fromUtf8("pushButtonAddLines"))
        self.gridLayout_3.addWidget(self.pushButtonAddLines, 1, 0, 1, 1)
        self.pushButtonExportData = QtGui.QPushButton(self.groupBoxEditTools)
        self.pushButtonExportData.setObjectName(_fromUtf8("pushButtonExportData"))
        self.gridLayout_3.addWidget(self.pushButtonExportData, 1, 1, 1, 1)
        self.pushButtonResetData = QtGui.QPushButton(self.groupBoxEditTools)
        self.pushButtonResetData.setObjectName(_fromUtf8("pushButtonResetData"))
        self.gridLayout_3.addWidget(self.pushButtonResetData, 2, 1, 1, 1)
        self.chkBoxSampleOriented = QtGui.QCheckBox(self.groupBoxEditTools)
        self.chkBoxSampleOriented.setObjectName(_fromUtf8("chkBoxSampleOriented"))
        self.gridLayout_3.addWidget(self.chkBoxSampleOriented, 1, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxEditTools)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tableWidgetData = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetData.sizePolicy().hasHeightForWidth())
        self.tableWidgetData.setSizePolicy(sizePolicy)
        self.tableWidgetData.setMinimumSize(QtCore.QSize(0, 500))
        self.tableWidgetData.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidgetData.setRowCount(0)
        #self.tableWidgetData.setColumnCount(25)
        self.tableWidgetData.setObjectName(_fromUtf8("tableWidgetData"))
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(0, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(1, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(2, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(3, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(4, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(5, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(6, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(7, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(8, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(9, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(10, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(11, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(12, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(13, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(14, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(15, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(16, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(17, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(18, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(19, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(20, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(21, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(22, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(23, item)
        # item = QtGui.QTableWidgetItem()
        # self.tableWidgetData.setHorizontalHeaderItem(24, item)
        self.verticalLayout_2.addWidget(self.tableWidgetData)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1139, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FDF - Field Data Formatter", None))
        self.groupBoxFileDetails.setTitle(_translate("MainWindow", "File details", None))
        self.labelInstrument.setText(_translate("MainWindow", "Instrument", None))
        self.labelFileLocation.setText(_translate("MainWindow", "File location", None))
        self.filePickerBtn.setText(_translate("MainWindow", "...", None))
        self.addFileBtn.setText(_translate("MainWindow", "Add file", None))
        self.labelCurrentFiles.setText(_translate("MainWindow", "Current files", None))
        self.groupBoxEditTools.setTitle(_translate("MainWindow", "Edit tools", None))
        self.pushButtonDeleteLines.setText(_translate("MainWindow", "Delete selected", None))
        self.pushButtonAddLines.setText(_translate("MainWindow", "Add lines", None))
        self.pushButtonExportData.setText(_translate("MainWindow", "Export data", None))
        self.pushButtonResetData.setText(_translate("MainWindow", "Reset data", None))
        self.chkBoxSampleOriented.setText(_translate("MainWindow", "Export sample-oriented file", None))
        # item = self.tableWidgetData.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "MP#", None))
        # item = self.tableWidgetData.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "Station#", None))
        # item = self.tableWidgetData.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "Date", None))
        # item = self.tableWidgetData.horizontalHeaderItem(3)
        # item.setText(_translate("MainWindow", "Time", None))
        # item = self.tableWidgetData.horizontalHeaderItem(4)
        # item.setText(_translate("MainWindow", "Sampling ID", None))
        # item = self.tableWidgetData.horizontalHeaderItem(5)
        # item.setText(_translate("MainWindow", "Location #", None))
        # item = self.tableWidgetData.horizontalHeaderItem(6)
        # item.setText(_translate("MainWindow", "Sequence #", None))
        # item = self.tableWidgetData.horizontalHeaderItem(7)
        # item.setText(_translate("MainWindow", "Matrix", None))
        # item = self.tableWidgetData.horizontalHeaderItem(8)
        # item.setText(_translate("MainWindow", "Sample type", None))
        # item = self.tableWidgetData.horizontalHeaderItem(9)
        # item.setText(_translate("MainWindow", "Calibration record", None))
        # item = self.tableWidgetData.horizontalHeaderItem(10)
        # item.setText(_translate("MainWindow", "Instrument", None))
        # item = self.tableWidgetData.horizontalHeaderItem(11)
        # item.setText(_translate("MainWindow", "Sampling officer", None))
        # item = self.tableWidgetData.horizontalHeaderItem(12)
        # item.setText(_translate("MainWindow", "Sample collected", None))
        # item = self.tableWidgetData.horizontalHeaderItem(13)
        # item.setText(_translate("MainWindow", "Depth upper (m)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(14)
        # item.setText(_translate("MainWindow", "Depth lower (m)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(15)
        # item.setText(_translate("MainWindow", "DO (mg/L)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(16)
        # item.setText(_translate("MainWindow", "DO (% sat)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(17)
        # item.setText(_translate("MainWindow", "pH", None))
        # item = self.tableWidgetData.horizontalHeaderItem(18)
        # item.setText(_translate("MainWindow", "Temp (deg C)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(19)
        # item.setText(_translate("MainWindow", "EC (uS/cm)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(20)
        # item.setText(_translate("MainWindow", "EC@25 (uS/cm)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(21)
        # item.setText(_translate("MainWindow", "Turbidity (NTU)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(22)
        # item.setText(_translate("MainWindow", "Water depth (m)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(23)
        # item.setText(_translate("MainWindow", "Gauge height (m)", None))
        # item = self.tableWidgetData.horizontalHeaderItem(24)
        # item.setText(_translate("MainWindow", "Comments", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

